### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#103]
![image](https://user-images.githubusercontent.com/757747/44516253-e294bf00-a6c4-11e8-80e6-a77c533ab6e9.png)

Synergy: pm2 3.0.0 - websocket 
Lambda: pm2 3.0.3 - agent 0.5.11 - websocket
Omicron: pm2 3.0.0 - agent 0.5.7 - websocket

All agents have leaked at the same time?

**Comment by Eywek** [comment]
seems fixed
