### ISSUE TITLE
options: allow configuration of logs broadcast

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#120]
- Environment variable
- pm2 set agent:log false
- ecosystem file? Retrieve option in agent (via status) and skip

**Comment by zamiang** [comment]
To add a bit more context on the use case (n=1), we are using PM2 to run a healthcare application. If we were to configure pm2 to report in a production capacity, our logs could sent protected health information (PHI) to Keymetrics when the log panel is open. That would be considered a data breach for us.

As you indicate, setting the agent to log=false (perhaps via the ecosystem config file?) would be ideal.

Thanks for filing this and I'm happy to deploy beta versions or help test.

**Comment by Eywek** [comment]
You will be able to disable logs sending like this:
```json
{
  "apps": [
    {
      "name": "app",
      "script": "app.js",
      "exec_mode": "fork",
      "env": { "send_logs": false }
    }
  ]
}
```

**Comment by Eywek** [comment]
Hi,

The @pm2/agent@0.5.24 is available with this feature (you can install it via `npm i -g pm2` and re-link via `pm2 link ...`).
