### ISSUE TITLE
Critical vulnerability in VM2, causing VM2 to be discontinued. Consider migrating to isolated-vm

### ISSUE THREAD

**Issue by OIRNOIR** [keymetrics/pm2-io-agent#132]
https://github.com/Unitech/pm2/issues/5639
VM2, used by pm2-io-agent, contains security vulnerabilities that will not be patched. Consider migrating to isolated-vm.

**Comment by OIRNOIR** [comment]
It appears that this project uses https://www.npmjs.com/package/proxy-agent which depends on vm2. Are there any alternatives?

**Comment by johnal95** [comment]
It seems the latest version of [proxy-agent](https://www.npmjs.com/package/proxy-agent) (`6.3.0`) no longer uses `vm2`:

https://github.com/TooTallNate/proxy-agents/releases

**Comment by deboyblog** [comment]
Can someone handle this pull request? #133
