### ISSUE TITLE
benchmark: agent verification

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#40]
## Axon

- [x] Verify that axon transporter stop buffering data when offline - OK
- [x] Verify that it does not leak memory when offline - OK
- [x] Verify that it switch to new url when agent is forwarded to another node & that all mechanism still works (reconnect, no leak) - OK
- [x] Verify that agent does not leak memory on the long run - OK (1hour check with 16 procs)

## Websocket

- [ ] Verify that websocket transporter stop buffering data when offline
- [ ] Verify that it does not leak memory when offline
- [x] Verify that agent does not leak memory on the long run
- [ ] Verify that it switch to new url when agent is forwarded to another node & that all mechanism still works (reconnect, no leak)

## General

- [x] [KO](https://github.com/keymetrics/keymetrics-agent/issues/42) Verify that unhandled exception does not stop crash the whole agent
- [x] [KO](https://github.com/keymetrics/keymetrics-agent/issues/44) Verify that when killing pm2, agent resurrect pm2
- [x] Verify that when overriding PM2_HOME, agent connect to the right PM2
- [ ] On slow network boot verify that agent try continuously to connect to backend
- [x] Verify that all necessary information is stored in agent configuration file
- [x] Save the specified backend endpoint when running in on-premise mode

**Comment by vmarchaud** [comment]
published under 0.5.0
