### ISSUE TITLE
q: handle error at the end?

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#54]
Write, publish then handle error at the end? That's a bad practice!

https://github.com/keymetrics/pm2-io-agent/blob/master/src/transporters/AxonTransport.js#L80

**Comment by vmarchaud** [comment]
There is no write, we just handle the way you implemented the authentification of the socket.
We dont handle errors because the sockets already handle the reconnection.
And only add the end, where we created all the callback needed, we connect.
I don't see why its a bad practice.
