### ISSUE TITLE
without connectivity, websocket think he's online + ping/pong system is not handled

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#57]
_ws.readyState is always equal to 1, making isConnected() always returning true, even when cutting internet connection

https://github.com/keymetrics/pm2-io-agent/blob/master/src/transporters/WebsocketTransport.js#L99

Also the on('ping') is never triggered:
https://github.com/keymetrics/pm2-io-agent/blob/master/src/transporters/WebsocketTransport.js#L78
But when working it will be great to verify internet connectivity

**Comment by vmarchaud** [comment]
https://github.com/websockets/ws/blob/master/doc/ws.md#ready-state-constants

**Comment by Eywek** [comment]
Couldn't reproduce
