### ISSUE TITLE
allow to switch between legacy agent (axon) / new agent (websocket) 

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#62]
Revertable commits:
https://github.com/Unitech/pm2/commit/dfb1f7ced88161f567988da0a5e5530d3d7171c7
https://github.com/Unitech/pm2/commit/299a52a253d70edcde23cbd7e0c201d492984df4

Very few changes have been done in term of integration to PM2 between the legacy agent and the websocket agent. So this revert and switch strategy should be easy to implement

**Comment by Eywek** [comment]
https://github.com/keymetrics/pm2-io-agent/pull/63
