### ISSUE TITLE
bucket upgrade: reduce time to reconnect to new endpoint

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#68]

**Comment by Unitech** [comment]
I reduced the refresh interval to one minute to avoid frustation for our new customers.
But I think the best would be to send a message to PM2 to tell it to connect to new node

**Comment by Unitech** [comment]
@vmarchaud @Eywek what's your ideas on this? Should we trigger a custom action to tell PM2 to refresh his endpoint after moving the bucket to another node?

**Comment by Eywek** [comment]
Will be fixed with new infrastructure

**Comment by vmarchaud** [comment]
We'll close when its actually fixed

**Comment by Eywek** [comment]
fixed, nomad-cluster is default node
