### ISSUE TITLE
The pm2 version is sometimes "undefined"

### ISSUE THREAD

**Issue by vmarchaud** [keymetrics/pm2-io-agent#84]
@BenoitZugmeyer commented on [Mon Jul 09 2018](https://github.com/keymetrics/km-api/issues/738)

User feedback:
<img width="585" alt="capture d ecran 2018-07-09 a 17 13 48" src="https://user-images.githubusercontent.com/61787/42462759-7091ad84-83a4-11e8-97b5-dbbf7c8071fe.png">

Bucket id: 5b04e3b59f65b63b4a49f897
User id: 5b04e3accd0ce01400b96790

In the realtime websocket, the server status sometimes includes "undefined" as pm2 version, see:

![screenshot_20180709_180835](https://user-images.githubusercontent.com/61787/42462742-65db39f0-83a4-11e8-81d9-d79314753dcf.png)

**Comment by vmarchaud** [comment]
should have been fixed with https://github.com/keymetrics/pm2-io-agent/commit/b87e6e6539c56bd0cec9926f18c3c5cf483d9ff5, could you confirm @BenoitZugmeyer  ?

**Comment by BenoitZugmeyer** [comment]
https://github.com/keymetrics/pm2-io-agent/commit/b87e6e6539c56bd0cec9926f18c3c5cf483d9ff5 seems to be about the node version, not the pm2 version.

**Comment by Eywek** [comment]
The pm2 version should be defined by pm2 (cf. https://github.com/keymetrics/pm2-io-agent/blob/master/src/InteractorDaemon.js#L279)

**Comment by Unitech** [comment]
will be fixed https://github.com/Unitech/pm2/pull/3799
