### ISSUE TITLE
Scoped actions don't work.

### ISSUE THREAD

**Issue by wallet77** [keymetrics/pm2-io-agent#86]
It seems scoped actions are correctly triggered by PM2 plus web interface.
But apm receive only action's name in listener (here https://github.com/keymetrics/pm2-io-apm/blob/a01b5f5d5bbdf80e44ebe3368e220e1947aae5f0/src/features/actions.ts#L41).

It should received an obect like this : 
```
{
  action_name: 'myaction',
  uuid: 'unique_id'
}
```

Link to : https://github.com/keymetrics/pm2-io-apm/issues/143

**Comment by Eywek** [comment]
Like this https://github.com/keymetrics/pm2-io-agent/blob/master/src/reverse/ReverseInteractor.js#L50 ?
