### ISSUE TITLE
agent.json5 got modified

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#90]
```
1238root@wakanda:/var/wakanda-hub/current# cat ~/.pm2/agent.json5 
1238root@wakanda:/var/wakanda-hub/current# cat ~/.pm2/agent.json5 
1238root@wakanda:/var/wakanda-hub/current# cat ~/.pm2/agent.json5 
```

**Comment by Eywek** [comment]
Can I have more explanations?

**Comment by Unitech** [comment]
It happened again. The computer that control the light at our office got stopped and could not link again to Keymetrics.

After inspection I saw that the ~/.pm2/agent.json5 file got overwritten with the pid??

```
⇄ root@orangepizero: ~
# cat .pm2/agent.json5 
2307
```

Re opening

**Comment by vmarchaud** [comment]
From the code, it  doesn't seems possible : https://github.com/keymetrics/pm2-io-agent/blob/997d0f5e4add768942bab90895974906b12efec1/src/InteractorClient.js#L379
Which version is running ?

**Comment by Unitech** [comment]
I don't have the exact version as I've updated pm2 to #development   

Weird, but I would image that INTERACTOR_PID_PATH get overwritten

https://github.com/keymetrics/pm2-io-agent/blob/997d0f5e4add768942bab90895974906b12efec1/src/InteractorClient.js#L206

**Comment by Eywek** [comment]
can't reproduce
